# Component bindings configuration
# This file maps interface types to concrete implementations

bindings:
  # Database implementations
  database: mongodb  # Options: mongodb
  
  # Memory implementations
  memory: mongo_memory  # Options: mongo_memory, custom_memory
  
  # Strategy implementations
  strategy: openai  # Options: openai, vertex, llama
  
  # Other components can be added as needed 